apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.65.4:6443
    kubernetes.io/config.hash: 8b71cd624d40d0ffecf5822890467a47
    kubernetes.io/config.mirror: 8b71cd624d40d0ffecf5822890467a47
    kubernetes.io/config.seen: "2023-06-12T09:33:26.777550841Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-06-12T09:33:43Z"
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver-docker-desktop
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: docker-desktop
    uid: 3d7cb886-bd7f-4314-91ea-7aa5c4e8e41f
  resourceVersion: "175277"
  uid: d0ff857a-75e3-4f33-82eb-c6172dd28f33
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.65.4
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/run/config/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction,NamespaceAutoProvision
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/run/config/pki/etcd/ca.crt
    - --etcd-certfile=/run/config/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/run/config/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --kubelet-client-certificate=/run/config/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/run/config/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/run/config/pki/front-proxy-client.crt
    - --proxy-client-key-file=/run/config/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/run/config/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/run/config/pki/sa.pub
    - --service-account-signing-key-file=/run/config/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/run/config/pki/apiserver.crt
    - --tls-private-key-file=/run/config/pki/apiserver.key
    - --watch-cache=false
    image: registry.k8s.io/kube-apiserver:v1.25.9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.65.4
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-apiserver
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 192.168.65.4
        path: /readyz
        port: 6443
        scheme: HTTPS
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 250m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 192.168.65.4
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /run/config/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /run/config/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-20T07:04:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-21T07:06:10Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-21T07:06:10Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-20T07:04:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://13372fcaba4ef363f1e352e50e50a05b426a6602b1f3bdc4da875b8aa1d4625d
    image: registry.k8s.io/kube-apiserver:v1.25.9
    imageID: docker://sha256:dc245db8c2faecaeac427ebcdf308ebe2c60e40728bf4f45f33d857ef3179969
    lastState:
      terminated:
        containerID: docker://5a13b7548ae368a4c639e0cc43e00ff046440d80261401ec755e95537cea942b
        exitCode: 0
        finishedAt: "2023-06-21T07:05:43Z"
        reason: Completed
        startedAt: "2023-06-20T07:04:41Z"
    name: kube-apiserver
    ready: true
    restartCount: 8
    started: true
    state:
      running:
        startedAt: "2023-06-21T07:05:51Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 192.168.65.4
  podIPs:
  - ip: 192.168.65.4
  qosClass: Burstable
  startTime: "2023-06-20T07:04:40Z"
